/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenTransactions.OTAPI {

public class BinaryPassword : Password {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal BinaryPassword(global::System.IntPtr cPtr, bool cMemoryOwn) : base(otapiPINVOKE.BinaryPassword_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BinaryPassword obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BinaryPassword() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otapiPINVOKE.delete_BinaryPassword(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BinaryPassword() : this(otapiPINVOKE.new_BinaryPassword__SWIG_0(), true) {
  }

  public BinaryPassword(SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t data) : this(otapiPINVOKE.new_BinaryPassword__SWIG_1(SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t.getCPtr(data)), true) {
    if (otapiPINVOKE.SWIGPendingException.Pending) throw otapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t getCopy() {
    SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t ret = new SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t(otapiPINVOKE.BinaryPassword_getCopy(swigCPtr), true);
    return ret;
  }

  public BinaryPassword(SWIGTYPE_p_void data, uint length) : this(otapiPINVOKE.new_BinaryPassword__SWIG_2(SWIGTYPE_p_void.getCPtr(data), length), true) {
  }

  public void append(SWIGTYPE_p_void data, uint length) {
    otapiPINVOKE.BinaryPassword_append(swigCPtr, SWIGTYPE_p_void.getCPtr(data), length);
  }

  public SWIGTYPE_p_std__pairT_void_pconst_size_t_const_t getMemoryCopy() {
    SWIGTYPE_p_std__pairT_void_pconst_size_t_const_t ret = new SWIGTYPE_p_std__pairT_void_pconst_size_t_const_t(otapiPINVOKE.BinaryPassword_getMemoryCopy__SWIG_0(swigCPtr), true);
    return ret;
  }

  public void getMemoryCopy(SWIGTYPE_p_p_void data, SWIGTYPE_p_size_t length) {
    otapiPINVOKE.BinaryPassword_getMemoryCopy__SWIG_1(swigCPtr, SWIGTYPE_p_p_void.getCPtr(data), SWIGTYPE_p_size_t.getCPtr(length));
    if (otapiPINVOKE.SWIGPendingException.Pending) throw otapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void getMemoryCopyOnto(SWIGTYPE_p_void data, uint length) {
    otapiPINVOKE.BinaryPassword_getMemoryCopyOnto(swigCPtr, SWIGTYPE_p_void.getCPtr(data), length);
  }

  public SWIGTYPE_p_std__basic_stringT_char_std__char_traitsT_char_t_secure_allocatorT_char_t_t toString() {
    SWIGTYPE_p_std__basic_stringT_char_std__char_traitsT_char_t_secure_allocatorT_char_t_t ret = new SWIGTYPE_p_std__basic_stringT_char_std__char_traitsT_char_t_secure_allocatorT_char_t_t(otapiPINVOKE.BinaryPassword_toString(swigCPtr), true);
    return ret;
  }

  public override uint length() {
    uint ret = otapiPINVOKE.BinaryPassword_length(swigCPtr);
    return ret;
  }

  public override void resize(uint nNewSize) {
    otapiPINVOKE.BinaryPassword_resize(swigCPtr, nNewSize);
  }

  public override void zero() {
    otapiPINVOKE.BinaryPassword_zero(swigCPtr);
  }

  public override bool randomize(uint nNewSize) {
    bool ret = otapiPINVOKE.BinaryPassword_randomize__SWIG_0(swigCPtr, nNewSize);
    return ret;
  }

  public bool randomize() {
    bool ret = otapiPINVOKE.BinaryPassword_randomize__SWIG_1(swigCPtr);
    return ret;
  }

}

}
