/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opentransactions.otapi;

public interface otapiConstants {
  public final static int OTPASSWORD_BLOCKSIZE = otapiJNI.OTPASSWORD_BLOCKSIZE_get();
  public final static String OT_PW_DISPLAY = otapiJNI.OT_PW_DISPLAY_get();
}
