/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opentransactions.otapi;

public class Password {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Password(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Password obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_Password(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getType() {
    return otapiJNI.Password_getType(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t getData() {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t(otapiJNI.Password_getData(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__pairT_void_pconst_size_t_const_t getMemory() {
    return new SWIGTYPE_p_std__pairT_void_pconst_size_t_const_t(otapiJNI.Password_getMemory__SWIG_0(swigCPtr, this), true);
  }

  public void getMemory(SWIGTYPE_p_p_void data, SWIGTYPE_p_size_t length) {
    otapiJNI.Password_getMemory__SWIG_1(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(data), SWIGTYPE_p_size_t.getCPtr(length));
  }

  public SWIGTYPE_p_std__pairT_void_const_pconst_size_t_const_t getMemoryConst() {
    return new SWIGTYPE_p_std__pairT_void_const_pconst_size_t_const_t(otapiJNI.Password_getMemoryConst__SWIG_0(swigCPtr, this), true);
  }

  public void getMemoryConst(SWIGTYPE_p_p_void data, SWIGTYPE_p_size_t length) {
    otapiJNI.Password_getMemoryConst__SWIG_1(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(data), SWIGTYPE_p_size_t.getCPtr(length));
  }

  public long length() {
    return otapiJNI.Password_length(swigCPtr, this);
  }

  public void resize(long arg0) {
    otapiJNI.Password_resize(swigCPtr, this, arg0);
  }

  public void zero() {
    otapiJNI.Password_zero(swigCPtr, this);
  }

  public boolean randomize(long arg0) {
    return otapiJNI.Password_randomize(swigCPtr, this, arg0);
  }

  public final static class TYPE {
    public final static int STRING = otapiJNI.Password_STRING_get();
    public final static int BINARY = otapiJNI.Password_BINARY_get();
  }

}
