/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opentransactions.otapi;

public class StringPassword extends Password {
  private long swigCPtr;

  protected StringPassword(long cPtr, boolean cMemoryOwn) {
    super(otapiJNI.StringPassword_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringPassword obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_StringPassword(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StringPassword() {
    this(otapiJNI.new_StringPassword__SWIG_0(), true);
  }

  public StringPassword(SWIGTYPE_p_std__basic_stringT_char_std__char_traitsT_char_t_secure_allocatorT_char_t_t data) {
    this(otapiJNI.new_StringPassword__SWIG_1(SWIGTYPE_p_std__basic_stringT_char_std__char_traitsT_char_t_secure_allocatorT_char_t_t.getCPtr(data)), true);
  }

  public StringPassword(SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t data) {
    this(otapiJNI.new_StringPassword__SWIG_2(SWIGTYPE_p_std__vectorT_unsigned_char_secure_allocatorT_unsigned_char_t_t.getCPtr(data)), true);
  }

  public SWIGTYPE_p_std__basic_stringT_char_std__char_traitsT_char_t_secure_allocatorT_char_t_t getCopy() {
    return new SWIGTYPE_p_std__basic_stringT_char_std__char_traitsT_char_t_secure_allocatorT_char_t_t(otapiJNI.StringPassword_getCopy(swigCPtr, this), true);
  }

  public String getChars() {
    return otapiJNI.StringPassword_getChars(swigCPtr, this);
  }

  public long length() {
    return otapiJNI.StringPassword_length(swigCPtr, this);
  }

  public void resize(long nNewSize) {
    otapiJNI.StringPassword_resize(swigCPtr, this, nNewSize);
  }

  public void zero() {
    otapiJNI.StringPassword_zero(swigCPtr, this);
  }

  public boolean randomize(long nNewSize) {
    return otapiJNI.StringPassword_randomize__SWIG_0(swigCPtr, this, nNewSize);
  }

  public boolean randomize() {
    return otapiJNI.StringPassword_randomize__SWIG_1(swigCPtr, this);
  }

}
